# -*- mode: ruby -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "debian10-gui" 
BOX_IMAGE = "generic/debian10" 
DISK_SIZE = "32GB"
MEMORY = 8192
CPU_CORES = 2

# port forwarding
SSH_PORT = 2210
#--------------------------------
# vm settings
# 1) ssh port forwarding
# 2) add tmpfs
# 3) use riken mirror
# 4) scp password authentication
# 5) install tool_packages for OpenRTM-aist core developer
# 6) install Japanese
# 7) install task-xfce-desktop
# 8) install adoptopenjdk-8-hotspot
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.disksize.size = DISK_SIZE
    node.vm.network :forwarded_port, id: "ssh", guest: 22, host: SSH_PORT
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.gui = true
      v.memory = MEMORY
      v.cpus = CPU_CORES
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    node.vm.provision "shell" ,inline: <<-SHELL
      # add tmpfs
      echo 'tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0' >> /etc/fstab

      # DNS config
      sed -ie 's/^#DNS=/DNS=150.29.246.19 150.29.254.121/g' /etc/systemd/resolved.conf
      systemctl restart systemd-resolved.service
      sed -ie 's/^nameserver/#nameserver/g' /etc/resolvconf/run/resolv.conf
      sed -ie '$anameserver 150.29.246.19' /etc/resolvconf/run/resolv.conf
      sed -ie '$anameserver 150.29.254.121' /etc/resolvconf/run/resolv.conf

      # use riken mirror
      sed -ie 's/^deb http/#deb http/g' /etc/apt/sources.list
      sed -ie 's/^deb-src http/#deb-src http/g' /etc/apt/sources.list
      sed -ie '$adeb http://ftp.riken.jp/pub/Linux/debian/debian buster main contrib non-free' /etc/apt/sources.list
      sed -ie '$adeb http://security.debian.org/ buster/updates main contrib non-free' /etc/apt/sources.list
      sed -ie '$a#deb-src http://ftp.riken.jp/pub/Linux/debian/debian buster main contrib non-free' /etc/apt/sources.list
      apt update
      DEBIAN_FRONTEND=noninteractive \
      apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -qq -y upgrade

      # time zone
      timedatectl set-timezone Asia/Tokyo

      # for password authentication with scp
      sed -ie 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd

      # install tool_packages for OpenRTM-aist core developer
      apt -y install wget
      wget https://raw.githubusercontent.com/OpenRTM/OpenRTM-aist/master/scripts/pkg_install_debian.sh -O pkg_install_debian.sh
      sh pkg_install_debian.sh -l c++ -l python -c --yes

      # openrtp depends on java8
      apt -y install apt-transport-https ca-certificates dirmngr gnupg software-properties-common
      wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
      add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
      apt update
      apt -y install adoptopenjdk-8-hotspot

      # Install Japanese
      apt -y install task-japanese

      # Locale setting
      $set_locale

      # desktop
      apt -y install task-xfce-desktop
    SHELL
  end
end


# Locale setting
#
$set_locale = <<SCRIPT
sed -i -e 's/# ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
update-locale LANG=ja_JP.UTF-8
localectl set-locale LANG=ja_JP.UTF-8
localectl set-keymap jp106
apt-get update
cat << EOF > /etc/default/keyboard
XKBMODEL="pc106"
XKBLAYOUT="jp"
XKBVARIANT=""
XKBOPTIONS=""
BACKSPACE="guess"
EOF
SCRIPT
