# -*- mode: ruby -*-
# -*- coding: utf-8 -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "ubuntu1604-32"
BOX_IMAGE = "ubuntu/xenial32"
DISK_SIZE = "32GB"
MEMORY = 2048
CPU_CORES = 1

# port forwarding
SSH_PORT = 21643
#--------------------------------
# vm settings
# 1) ssh port forwarding
# 2) add tmpfs
# 3) use riken mirror
# 4) scp password authentication
# 5) install tool_packages for OpenRTM-aist core developer
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.disksize.size = DISK_SIZE
    node.vm.network :forwarded_port, id: "ssh", guest: 22, host: SSH_PORT
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.memory = MEMORY
      v.cpus = CPU_CORES
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    node.vm.synced_folder "./share", "/home/vagrant/share",
    create: true, owner: "vagrant", group: "vagrant"

    node.vm.provision "shell" ,inline: <<-SHELL
      # add tmpfs
      echo 'tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0' >> /etc/fstab
      # use riken mirror
      sed -i -e 's%archive.ubuntu.com/ubuntu%ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
      apt update

      # time zone
      timedatectl set-timezone Asia/Tokyo

      # scp password authentication
      sed -ie 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd

      # install tool_packages for OpenRTM-aist core developer
      apt -y install wget
      wget --secure-protocol=TLSv1_2 --no-check-certificate https://raw.githubusercontent.com/OpenRTM/OpenRTM-aist/master/scripts/pkg_install_ubuntu.sh -O pkg_install_ubuntu.sh
      sh pkg_install_ubuntu.sh -l c++ -l python -c --yes
    SHELL

  end
end