# -*- mode: ruby -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "u1804-gui-nat"
BOX_IMAGE = "ubuntu/bionic64"
DISK_SIZE = "32GB"
MEMORY = 8192
CPU_CORES = 32

# port forwarding
SSH_PORT = 21842
#--------------------------------
# vm settings
# 1) ssh port forwarding
# 2) add tmpfs
# 3) use riken mirror
# 4) install ubuntu-desktop
# 5) libssl installs non-interactively
# 6) scp password authentication
# 7) install tool_packages for OpenRTM-aist core developer
# 8) install openjdk-8-jdk
# 9) Keyboard japanese layout
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.disksize.size = DISK_SIZE
    node.vm.network :forwarded_port, id: "ssh", guest: 22, host: SSH_PORT
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.gui = true
      v.memory = MEMORY
      v.cpus = CPU_CORES
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    node.vm.provision "shell" ,inline: <<-SHELL
      # add tmpfs
      echo 'tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0' >> /etc/fstab
      # use riken mirror
      sed -i -e 's%archive.ubuntu.com/ubuntu%ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
      apt update

      # libssl installs non-interactively
      UCF_FORCE_CONFOLD=1 \
      DEBIAN_FRONTEND=noninteractive \
      apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -qq -y install libssl1.1
      apt -y upgrade

      # desktop
      apt -y install ubuntu-desktop
      # time zone
      timedatectl set-timezone Asia/Tokyo

      # scp password authentication
      sed -ie 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd

      # install tool_packages for OpenRTM-aist core developer
      apt -y install wget
      wget https://raw.githubusercontent.com/OpenRTM/OpenRTM-aist/master/scripts/pkg_install_ubuntu.sh -O pkg_install_ubuntu.sh
      sh pkg_install_ubuntu.sh -l c++ -l python -c --yes

      # openrtp depends on java8
      add-apt-repository ppa:openjdk-r/ppa -y
      apt update
      apt -y install openjdk-8-jdk
      JAVA8=`update-alternatives --list java | grep java-8`
      update-alternatives --set java ${JAVA8}

      # Keyboard japanese layout
      echo 'setxkbmap -layout jp' >> /home/vagrant/.bashrc

    SHELL
  end
end