# -*- mode: ruby -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "ubuntu1804"
BOX_IMAGE = "ubuntu/bionic64"
IPADDRESS = "192.168.33.24"
SSH_PORT = 22184
#--------------------------------
DISK_SIZE = "32GB"
MEMORY = 2048
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.disksize.size = DISK_SIZE
    node.vm.network "private_network", ip: IPADDRESS
    node.vm.network :forwarded_port, id: "ssh", guest: 22, host: SSH_PORT
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.memory = MEMORY
    end

    node.vm.provision "shell" ,inline: <<-SHELL
      # time zone
      timedatectl set-timezone Asia/Tokyo

      # for password authentication with scp
      sed -ie 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd

      # install tool_packages for OpenRTM-aist core developer
      apt-get update
      apt-get install -y wget ant
      wget https://raw.githubusercontent.com/OpenRTM/OpenRTM-aist/master/scripts/pkg_install_ubuntu.sh -O pkg_install_ubuntu.sh
      sh pkg_install_ubuntu.sh -l c++ -l python -c --yes

      # openrtp depends on java8
      add-apt-repository ppa:openjdk-r/ppa -y
      apt-get update
      apt-get -y install openjdk-8-jdk
      JAVA8=`update-alternatives --list java | grep java-8`
      update-alternatives --set java ${JAVA8}
    SHELL

  end
end