# -*- mode: ruby -*-
# -*- coding: utf-8 -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "u2404-eclipse416"
BOX_IMAGE = "gusztavvargadr/ubuntu-server-2404-lts"
BOX_VER = "2509.0.0"

DISK_SIZE = "10GB"
MEMORY = 4096

# port forwarding
SSH_PORT = 24041

# Language package
#--------------------------------
# vm settings
# 1) ssh port forwarding
# 2) add tmpfs
# 3) use riken mirror
# 5) libssl installs non-interactively
# 6) scp password authentication
# 7) install tool_packages for OpenRTM-aist core developer
# 8) install openjdk-8-jdk
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.vm.box_version = BOX_VER
    node.vm.network :forwarded_port, id: "ssh", guest: 22, host: SSH_PORT
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.memory = MEMORY
      v.customize ["modifyvm", :id, 
        "--cpus", "2",
        "--vram", "256",
        "--accelerate3d", "on",
        "--ioapic", "on",
        "--chipset", "ich9",
        "--paravirtprovider", "kvm",
        "--clipboard", "bidirectional"
      ]
    end
    node.vm.boot_timeout = 600

    node.vm.provision "shell" ,inline: <<-SHELL
      # add tmpfs
      echo 'tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0' >> /etc/fstab
      # use riken mirror
      sed -i -e 's%archive.ubuntu.com/ubuntu%ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
      apt update

      # libssl installs non-interactively
      UCF_FORCE_CONFOLD=1 \
      DEBIAN_FRONTEND=noninteractive \
      apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -qq -y install libssl1.1
      apt -y upgrade

      # time zone
      timedatectl set-timezone Asia/Tokyo

      # for password authentication with scp
      sed -ie 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd

      # install tool_packages for OpenRTM-aist core developer
      apt -y install wget ant zip
      wget --secure-protocol=TLSv1_2 --no-check-certificate https://raw.githubusercontent.com/OpenRTM/OpenRTM-aist/master/scripts/openrtm2_install_ubuntu.sh -O openrtm2_install_ubuntu.sh
      sh openrtm2_install_ubuntu.sh -l c++ -l python -c --yes

      # openrtp depends on java8
      apt -y install openjdk-8-jdk
      JAVA8=`update-alternatives --list java | grep java-8`
      update-alternatives --set java ${JAVA8}
    SHELL

    node.vm.provision "shell", privileged: false, inline: <<-SHELL
      # Eclipse SDK, RCP Download
      ECLIPSE_VER="2020-06"
      DEST_DIR=${HOME}/public_html/pub/eclipse/packages

      SDK_URL="https://archive.eclipse.org/eclipse/downloads/drops4/R-4.16-202006040540/"
      LINUX_SDK="eclipse-SDK-4.16-linux-gtk-x86_64.tar.gz"
      WINDOWS_SDK="eclipse-SDK-4.16-win32-x86_64.zip"

      RCP_URL="https://archive.eclipse.org/technology/epp/downloads/release/2020-06/R/"
      RCP_FILE="eclipse-rcp-2020-06-R-linux-gtk-x86_64.tar.gz"

      BABEL_URL="https://archive.eclipse.org/technology/babel/babel_language_packs/R0.18.1/2020-06/"
      LANG_PACKAGE="BabelLanguagePack-eclipse-ja_4.16.0.v20201010073410.zip"

      mkdir -p ${DEST_DIR}
      wget -P ${DEST_DIR} ${SDK_URL}/${LINUX_SDK}
      wget -P ${DEST_DIR} ${SDK_URL}/${WINDOWS_SDK}
      wget -P ${DEST_DIR} ${RCP_URL}/${RCP_FILE}
      wget -P ${DEST_DIR} ${BABEL_URL}/${LANG_PACKAGE}

      # deploy Eclipse --- $HOME/eclipse
      cp ${DEST_DIR}/${LINUX_SDK} .
      tar zxvf ${LINUX_SDK}

      # deploy Eclipse --- $HOME/eclipse_env
      ENV_DIR=${HOME}/eclipse_env
      mkdir ${ENV_DIR}
      cp ${DEST_DIR}/${RCP_FILE} ${ENV_DIR}/
      tar zxvf ${ENV_DIR}/${RCP_FILE} -C ${ENV_DIR}/

      # get scripts
      wget https://raw.githubusercontent.com/OpenRTM/OpenRTP-aist/master/mirror_site
      wget https://raw.githubusercontent.com/OpenRTM/OpenRTP-aist/master/install_plugins

      # download software site repository
      ECLIPSE_SOFT_REPO=https://download.eclipse.org/releases/${ECLIPSE_VER}
      MIRROR_DIR=${HOME}/public_html/pub/eclipse/projects/${ECLIPSE_VER}
      export ECLIPSE_HOME=${HOME}/eclipse_envs/eclipse
      bash mirror_site ${ECLIPSE_SOFT_REPO} ${MIRROR_DIR}

      # install Eclipse plugins
      export REPOSITORY="file:///${MIRROR_DIR},${ECLIPSE_SOFT_REPO}"
      sh install_plugins ${HOME}/eclipse
    SHELL
  end
end
