# -*- mode: ruby -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "u1804-rd"
BOX_IMAGE = "ubuntu/bionic64"
DISK_SIZE = "32GB"
MEMORY = 10240
CPU_CORES = 32

#--------------------------------
# vm settings
# 1) public network (bridge)
# 2) add tmpfs
# 3) use riken mirror
# 4) install ubuntu-desktop
# 5) libssl installs non-interactively
# 6) scp password authentication
# 7) install tool_packages for OpenRTM-aist core developer
# 8) install remote desktop
# 9) install openjdk-8-jdk
# 10) Keyboard japanese layout
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.disksize.size = DISK_SIZE
    node.vm.network "public_network"
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.gui = true
      v.memory = MEMORY
      v.cpus = CPU_CORES
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    node.vm.provision "shell" ,inline: <<-SHELL
      # add tmpfs
      echo 'tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0' >> /etc/fstab
      # use riken mirror
      sed -i -e 's%archive.ubuntu.com/ubuntu%ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
      apt update

      # libssl installs non-interactively
      UCF_FORCE_CONFOLD=1 \
      DEBIAN_FRONTEND=noninteractive \
      apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -qq -y install libssl1.1
      apt -y upgrade

      # desktop
      apt -y install ubuntu-desktop
      # time zone
      timedatectl set-timezone Asia/Tokyo

      # scp password authentication
      sed -ie 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd

      # install tool_packages for OpenRTM-aist core developer
      apt -y install wget
      wget https://raw.githubusercontent.com/OpenRTM/OpenRTM-aist/master/scripts/pkg_install_ubuntu.sh -O pkg_install_ubuntu.sh
      sh pkg_install_ubuntu.sh -l c++ -l python -c --yes

      # install remote desktop
      apt -y install xorgxrdp xrdp
      # Display correction around cursor
      sed -i -e 's/^new_cursors=true/new_cursors=false/g' /etc/xrdp/xrdp.ini
      systemctl restart xrdp

      # openrtp depends on java8
      # JDK8 is installed with pkg_install_ubuntu.sh.

      # Keyboard japanese layout
      echo 'setxkbmap -layout jp' >> /home/vagrant/.bashrc
      # Install Japanese
      apt -y install language-pack-ja language-pack-gnome-ja
      # config Env
      update-locale LANG=ja_JP.UTF-8

      # change themes
      apt -y install gnome-tweak-tool
    SHELL

    # Avoiding 'Authentication Required' dialog
    node.vm.provision "shell" ,inline: $avoid_authentication_required
  end
end

$avoid_authentication_required = <<SCRIPT
cat <<EOF >> /etc/polkit-1/localauthority/50-local.d/xrdp-color-manager.pkla
[Netowrkmanager]
Identity=unix-user:*
Action=org.freedesktop.color-manager.create-device
ResultAny=no
ResultInactive=no
ResultActive=yes
EOF
SCRIPT
