# -*- mode: ruby -*-
# -*- coding: utf-8 -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "build-openrtp2-eclipse416"
BOX_IMAGE = "openrtp2-eclipse416-u2404"
BOX_URL = "https://openrtm.org/pub/openrtp/vagrant-box/openrtp2-eclipse416-u2404.box"
MEMORY = 4096

# port forwarding
SSH_PORT = 22444
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.vm.box_url = BOX_URL
    node.vm.network :forwarded_port, id: "ssh", guest: 22, host: SSH_PORT
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.memory = MEMORY
      v.gui = true

      # Serial port activation off
      v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    node.vm.boot_timeout = 600
    node.vm.synced_folder "./share", "/home/vagrant/share", create: true, owner: "vagrant", group: "vagrant"
    node.vm.synced_folder "./scripts", "/home/vagrant/scripts", create: true, owner: "vagrant", group: "vagrant"
  end
end
