# -*- mode: ruby -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "ubuntu1804gui"
BOX_IMAGE = "ubuntu/bionic64"
IPADDRESS = "192.168.33.26"
SSH_PORT = 21842
#--------------------------------
DISK_SIZE = "32GB"
MEMORY = 4096
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.disksize.size = DISK_SIZE
    node.vm.network "private_network", ip: IPADDRESS
    node.vm.network :forwarded_port, id: "ssh", guest: 22, host: SSH_PORT
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.gui = true
      v.memory = MEMORY
    end

    # for password authentication with scp
    node.vm.provision "shell" do |shell|
      shell.inline = <<-SHELL
        # desktop
        apt-get update
        apt-get -y install ubuntu-desktop
        # timezone
        timedatectl set-timezone Asia/Tokyo

        # for password authentication with scp
        sed -ie 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
      SHELL
    end

    # install tool_packages for OpenRTM-aist core developer
    node.vm.provision "shell" do |shell|
      shell.path = "./provision/pkg_install_ubuntu.sh" 
      shell.args = "-l c++ -l python -c --yes" 
    end

    # install opencv3 java8 rtctree
    node.vm.provision "shell" do |shell|
      shell.path = "./provision/pkg_install_ubuntu1804_RTC_test.sh" 
    end
  end
end