# -*- mode: ruby -*-
# -*- coding: utf-8 -*-
# vi: set ft=ruby :

#--------------------------------
VM_NAME = "u1804-ros2"
BOX_IMAGE = "ubuntu/bionic64"
DISK_SIZE = "32GB"
MEMORY = 8192
CPU_CORES = 2

# port forwarding
SSH_PORT = 31841
#--------------------------------
# vm settings
# 1) ssh port forwarding
# 2) add tmpfs
# 3) use riken mirror
# 4) install ubuntu-desktop
# 5) libssl installs non-interactively
# 6) scp password authentication
# 7) install tool_packages for OpenRTM-aist core developer
# 8) install openjdk-8-jdk
# 9) install ROS2
# 10) Keyboard japanese layout
#--------------------------------

Vagrant.configure("2") do |config|

  config.vm.define VM_NAME do |node|
    node.vm.hostname = VM_NAME
    node.vm.box = BOX_IMAGE
    node.disksize.size = DISK_SIZE
    node.vm.network :forwarded_port, id: "ssh", guest: 22, host: SSH_PORT
    node.vm.provider "virtualbox" do |v|
      v.name = VM_NAME
      v.gui = true
      v.memory = MEMORY
      v.cpus = CPU_CORES
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    node.vm.boot_timeout = 600
    node.vm.synced_folder "./share", "/home/vagrant/share", create: true, owner: "vagrant", group: "vagrant"

    node.vm.provision "shell" ,inline: <<-SHELL
      # add tmpfs
      echo 'tmpfs /tmp tmpfs rw,nodev,nosuid,size=512M 0 0' >> /etc/fstab
      # use riken mirror
      sed -i -e 's%archive.ubuntu.com/ubuntu%ftp.riken.go.jp/Linux/ubuntu/%g' /etc/apt/sources.list
      apt update

      # libssl installs non-interactively
      UCF_FORCE_CONFOLD=1 \
      DEBIAN_FRONTEND=noninteractive \
      apt -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -qq -y install libssl1.1
      apt -y upgrade

      # desktop
      apt -y install ubuntu-desktop
      # time zone
      timedatectl set-timezone Asia/Tokyo

      # scp password authentication
      sed -ie 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
      systemctl restart sshd

      # install tool_packages for OpenRTM-aist core developer
      apt -y install wget ant junit

      wget --secure-protocol=TLSv1_2 --no-check-certificate https://raw.githubusercontent.com/OpenRTM/OpenRTM-aist/master/scripts/pkg_install_ubuntu.sh -O pkg_install_ubuntu.sh
      sh pkg_install_ubuntu.sh -l c++ -l python -c --yes

      # openrtp depends on java8
      # install openjdk
      apt -y install openjdk-8-jdk
      JAVA8=`update-alternatives --list java | grep java-8`
      update-alternatives --set java ${JAVA8}

      # install ROS2(dashing)
      apt -y install curl gnupg2
      curl http://repo.ros2.org/repos.key | apt-key add -
      sh -c 'echo "deb http://repo.ros2.org/ubuntu/main bionic main" > /etc/apt/sources.list.d/ros2-latest.list'
      apt update
      apt -y install ros-dashing-desktop python3-colcon-common-extensions python3-argcomplete
      echo "source /opt/ros/dashing/setup.bash" >> /home/vagrant/.bashrc

      # Keyboard japanese layout
      apt -y install ibus-mozc
      echo 'setxkbmap -layout jp' >> /home/vagrant/.bashrc

    SHELL
  end
end